#+TITLE: P4P 初诊报告
#+DATE: 2023-07-17
#+KEYWORDS: Alibaba, P4P

** 一、店铺流量情况
 
上面是店铺近2月主营类目与同行数据的对比情况，店铺的提升的方向就是从 流量→点击率→转化 这样一个过程，接下来流量端口是重点，持续提升平台效果品是后续的方向。
国际站流量分2种，自然流量和付费流量。自然流量是通过产品自然搜索，定向征品主题，自营销（粉丝通，访客营销，RFQ），活动，直播等场景。日常要多去关注自然流量，通过主动的一些操作来获取。付费流量就是顶展，问鼎，直通车等一些营销工具，当前可以先用直通车来辅助提升。


** 二、行业市场情况：
从近30天行业TM咨询来看，俄罗斯联邦、巴基斯坦、美国、印度、孟加拉国、哈萨克斯坦较多，也可以先根据线下订单出口较多的国家定主推市场，根据产品的不同，市场的不同精准引流，这样才能把产品效果提到最大。这也是我们后续直通车推广前要确认好主打市场比较重要的部分。
 
6月TM咨询来看，亚欧地区占比大，上面行业情况也看得到，如果要以询盘/订单转化为目标提升，从大的方向看，我们的流量要更多引入亚欧地区，当然其他市场也是潜在的，只是说前期先以高转化国家为导向平台数据提升快一些，后期流量饱和之后可以再拓展。


** 三、产品端口：
1、店铺折扣优惠券：建议把折扣优惠券信息以及产品导购板块加上，之后参与官方活动或者商家自主设置的优惠信息都会自动展示的，吸引买家进店查看。
  
2、文案打造：建议图文结合，因为国外网络的是没有我们内好的，如果都是图片显示不出来会影响买家观感，另外文字用手打的是可以转换翻译的，便于买查看。不需要全部的产品都这样做，之后可以挑选几款店铺数据较好（询盘/订单/点击率），且线下订单较多的款式详情页加入文字描述，从产品卖点，使用特性，买家疑难点入手编写即可，有助于SEO搜索排序。也可多去看看同行优质产品是怎么去展示的，不要去复制直接抄文案，因为会有重复率问题限流，最好贴合自己产品编写。
 
3、选品推广：有3种方式，
- 查看平台数据较好的产品（主观）
- 通过直通车计划测出高潜款式
- 通过数据参谋或者其他软件辅助查看通过趋势品。

平台目前数据积累较少，大部分是新发品前期可以用 新品成长计划 推广主打款，在数据积累的同时测出高潜款式，可以作为我们之后的重点推广选品的参考。
 
（筛选点击降序，截屏转化率低的产品）这些产品是我们近期转化比较差的，需要优化。产品优化的方向主要是两个点，一是词来源，在产品360分析中，如果出现了高点击词无转化的情况，当一个词一个月左右的时间都是他点击高无转化的时候，暂停直通车推广。二是，检查词匹配的情况下，核心还是做产品优化的动作，比如说主图视频绑定，详情页视频绑定，详情页添加好评板块等。
 
（筛选周或者月询盘转化率数据，截屏靠前的结果）上面这个类型的产品建议多关注，6月都有来询盘且询盘转化率高，可以通过加入橱窗、旺铺首页单独设计海报/前排展示、edm营销推荐、活动报名、tips自营销方式等引流，也可以单独建立一个直通车计划重点推广。


** 四、直通车优化建议：
 
上面是近7天直通车同行流量对比情况，店铺直通车点击率0.31%还有较大的提升空间，点击率同行平均在0.51%左右，同行优秀在1.38%左右。直通车效果好不好首先看的指标也是点击率，只有买家先点进来才有机会发询盘或者下单，当然这也不是绝对的，因为现在是千人千面的流量场景，通过大数据匹配买家点击率会下来一些，不过可以通过调整维持的。

计划优化建议：
 
1.	定期检查低星词问题（0-2星），最少一周一次，暂停低星词，低星词不好的影响主要是这两个点，一是无法进入前五的主搜区，不能获得优质流量；二是基于扣费公式，会造成更高花费的点击，所以低星词一定要暂停，优化后推广，优化的方向：-1.类名匹配；-2.完整出现在标题里；-3.完整出现在关键词里；达成这三个条件可以达到3星，3-5星看这个词的数据，买家喜好度等因素，商家不可控。
 
2.	重点国家人群进行侧重溢价，不低于溢价建议，后续再根据数据情况调整。

 
3.	基于词报告，高点击无意向商机或者低意向商机转化的词，观察2-3周，部分效果较差的词暂停推广。衡量是否优秀，以20%的转化为基准，也就是10个点击带来2-3个意向商机是还不错的，也可以在账户分析中的引流能力对比同行和优秀商机转化的数据，会更为准确。


** 五、品牌广告优化建议：
目前我们家还未投放广告相关的内容，国际站广告的核心是两种，一个是效果广告，就是我们日常推广的直通车，一个是品牌广告，比如说问鼎、顶展等，他们不单单可以提高我们对应品的曝光展示，对我们品牌的打造，店铺实力展示都是有帮助的，历史记录比较好的词，可以联系咱们的客户经理，咨询一下近期该词的情况


** 六、总结
1.对标同行优秀的转化率，优化产品价格起订量、内页、视频等
2.转化率更好的产品建议放在旺铺、橱窗、直通车中展示；
3.调整推广的地域，优先对转化效果更好的地域溢价；
4.根据直通车优化建议调整，养成习惯，每周至少2-3次观察直通车数据。


